'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AllotRoom

    '''<summary>
    '''TxtBookingNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtBookingNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RfvBookingId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RfvBookingId As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BtnCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCheck As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdCustomerDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdCustomerDetails As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''PnlCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlCustomers As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''LblName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMobile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblMail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblRoomType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblRoomType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblNumOfRooms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblNumOfRooms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblAdult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAdult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblChild control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblChild As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblCkeckIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCkeckIn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtCheckInTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCheckInTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblCheckOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCheckOut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtCheckOutTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCheckOutTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LblTotalAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTotalAmt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtAdvance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtAdvance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblRemainingAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblRemainingAmt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''BtnOccupyRoom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnOccupyRoom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnVacate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnVacate As Global.System.Web.UI.WebControls.Button
End Class
